github:
  token: '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'
  username: 'DolevGabay'
  repo_visibility: 'varonis'
  repo_protection: 'sigh-up'
  branch: 'main'
  ssh_key_title: 'my-laptop-ssh-key' 
  ssh_key_path: '~/.ssh/id_rsa.pub'
